global:
  scrape_interval: 20s
  scrape_timeout: 15s
  
remote_write:
  - url: "http://0.0.0.0:9090/api/v1/write"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6forapi:5665']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
